export const LOAD_FRIENDS_LIST = "LOAD_FRIENDS_LIST";
export const ADD_ID_FRIENDS_FILTER = "ADD_ID_FRIENDS_FILTER";
export const REMOVE_ID_FRIENDS_FILTER = "REMOVE_ID_FRIENDS_FILTER";
export const CHANGE_SEARCH_WORD = "CHANGE_SEARCH_WORD";
export const CHANGE_SEARCH_WORD_FILTER = "CHANGE_SEARCH_WORD_FILTER";
export const LOAD_FILTERED_IDS = "LOAD_FILTERED_IDS";
export const CHANGE_DRAGGABLE_ID = "CHANGE_DRAGGABLE_ID";
export const UPDATE_FILTER_BY_DRAG = "UPDATE_FILTER_BY_DRAG";