export const LOAD_FRIENDS_LIST = "LOAD_FRIENDS_LIST";
export const ADD_ID_FRIENDS_FILTER = "ADD_ID_FRIENDS_FILTER";
export const REMOVE_ID_FRIENDS_FILTER = "REMOVE_ID_FRIENDS_FILTER";
export const CHANGE_SEARCH_WORD = "CHANGE_SEARCH_WORD";
export const CHANGE_SEARCH_WORD_FILTER = "CHANGE_SEARCH_WORD_FILTER";